import ProjectGrid from './ProjectGrid';

export default function WebsiteProjects() {
  const projects = [
    {
      title: "Kabar Baik Studio — Digital Wedding Invitation Platform",
      image: "/assets/projects/kabarbaik.png",
      roles: ["Founder", "Product Owner", "Full-Stack Developer"],
      desc: "Founded and independently built a live digital wedding invitation platform. End-to-end ownership from requirements definition through design, development, and deployment. Responsible for gathering client requirements, translating them into product features, managing the roadmap, and overseeing delivery. Currently serving real clients via kabarbaik.web.id.",
      tech: ["React.js", "Tailwind CSS", "Figma", "Requirements Analysis", "Product Management"],
      link: "https://kabarbaik.web.id/",
      linkText: "Kunjungi Website",
    },
    {
      title: "FaceDX – Website Deteksi & Perawatan Kulit Berbasis AI",
      image: "/assets/projects/webfacedx.png",
      roles: ["Full-Stack Developer", "AI/ML Developer", "UI/UX Designer"],
      desc: "Proyek skripsi: platform deteksi kondisi kulit wajah berbasis deep learning dengan akurasi model 90%. Bertanggung jawab atas full product lifecycle — dari requirements gathering, desain sistem, pengembangan (React + Flask + Python), hingga deployment dan penulisan jurnal ilmiah.",
      tech: ["React.js", "Tailwind CSS", "Flask", "Python", "Deep Learning", "Figma"],
      link: "https://facedx.web.id/",
      linkText: "Kunjungi Website",
    },
    {
      title: "Placement Test & IELTS Platform — Scholarstoday.id",
      image: "/assets/projects/Schoolars.png",
      roles: ["Product Support Intern", "Front-End Developer", "UI/UX Collaborator"],
      desc: "Berkontribusi sebagai Product Support Intern pada platform beasiswa live yang melayani 1,000+ pengguna. Menerjemahkan prototipe Figma menjadi spesifikasi implementasi, memfasilitasi usability testing dengan 50+ pengguna, dan berkontribusi langsung pada pengiriman modul scholar profiles, event dashboard, dan donation menggunakan React & Tailwind CSS.",
      tech: ["Figma", "React.js", "Tailwind CSS", "Agile/Scrum", "Usability Testing"],
      link: "https://scholarstoday.id/",
      linkText: "Kunjungi Website",
    },
    {
      title: "Profile AMKS",
      image: "/assets/projects/Amkss.png",
      roles: ["Front-End Developer", "UI/UX Designer"],
      desc: "Merancang dan mengembangkan website profil asrama AMKS menggunakan React.js dan Tailwind CSS. Melakukan requirements gathering dengan pengurus asrama, mendefinisikan user stories, dan menghasilkan desain di Figma sebelum implementasi.",
      tech: ["Figma", "React.js", "Tailwind CSS"],
      link: "https://www.amks.web.id/",
      linkText: "Kunjungi Website",
    },
    {
      title: "WebAPP Edufarm",
      image: "/assets/projects/EduFarm.png",
      roles: ["UI/UX Designer", "Front-End Developer"],
      desc: "Berkolaborasi dalam tim untuk mengembangkan platform pembelajaran pertanian Edufarm. Bertanggung jawab atas desain responsif web & mobile serta front-end development dengan React.js.",
      tech: ["React.js", "Tailwind CSS", "Figma"],
      link: "https://edufarm-ramas-projects-5fc87afb.vercel.app/",
      linkText: "Kunjungi Website",
      extraLink: "https://appetize.io/app/b_f74czjtfovtbemmnhbh3xrug2m",
      extraLinkText: "Preview Aplikasi",
    },
    {
      title: "Website Katalog Sonbros Wedding",
      image: "/assets/projects/sonbros.png",
      roles: ["Founder", "Full-Stack Developer"],
      desc: "Mendirikan dan mengembangkan website katalog undangan pernikahan Sonbros. Proyek ini menjadi cikal bakal Kabar Baik Studio — pengalaman pertama mengelola digital product dari idea hingga go-live.",
      tech: ["React.js", "Tailwind CSS", "Figma"],
      link: "https://www.sonbrosweding.my.id/",
      linkText: "Kunjungi Website",
    },
    {
      title: "Website Katalog Kress",
      image: "/assets/projects/kress.png",
      roles: ["Full-Stack Developer"],
      desc: "Mengembangkan website katalog untuk Kress (kripik singkong) dengan antarmuka dinamis menggunakan React.js.",
      tech: ["React.js"],
      link: "https://kress.vercel.app",
      linkText: "Kunjungi Website",
    },
    {
      title: "Proyek Website Yearbook Asrama AMKS",
      image: "/assets/projects/amks.png",
      roles: ["Full-Stack Developer", "UI/UX Designer"],
      desc: "Mengembangkan website yearbook responsif untuk Asrama AMKS menggunakan HTML dan CSS, dengan desain high-fidelity yang mencerminkan semangat komunitas.",
      tech: ["HTML", "CSS"],
      link: null,
      linkText: null,
    },
    {
      title: "Proyek Website Wisata Lokal",
      image: "/assets/projects/travel.png",
      roles: ["Front-End Developer", "UI/UX Designer"],
      desc: "Mengembangkan website wisata lokal menggunakan PHP, HTML, CSS, dan Bootstrap untuk tampilan responsif dan intuitif.",
      tech: ["PHP", "HTML", "CSS", "Bootstrap"],
      link: null,
      linkText: null,
    },
  ];

  return <ProjectGrid projects={projects} />;
}